// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD60RHa-YG8_w78rbuSOBDJ1TxERyp4nkg',
    appId: '1:874445302227:web:53d986dee5be04cb8b2726',
    messagingSenderId: '874445302227',
    projectId: 'code-burguer',
    authDomain: 'code-burguer.firebaseapp.com',
    storageBucket: 'code-burguer.firebasestorage.app',
    measurementId: 'G-GWCZXJBHRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1tMmylz4NeHYUpvt6hNMXr3DnQ3TRKU',
    appId: '1:874445302227:android:ecc4cf6c03b72de78b2726',
    messagingSenderId: '874445302227',
    projectId: 'code-burguer',
    storageBucket: 'code-burguer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6myCLjkoAMwtpu0vxgb9k_lXD-NZGLR8',
    appId: '1:874445302227:ios:27a0469cf113819c8b2726',
    messagingSenderId: '874445302227',
    projectId: 'code-burguer',
    storageBucket: 'code-burguer.firebasestorage.app',
    iosBundleId: 'com.example.codeBurguer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6myCLjkoAMwtpu0vxgb9k_lXD-NZGLR8',
    appId: '1:874445302227:ios:27a0469cf113819c8b2726',
    messagingSenderId: '874445302227',
    projectId: 'code-burguer',
    storageBucket: 'code-burguer.firebasestorage.app',
    iosBundleId: 'com.example.codeBurguer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD60RHa-YG8_w78rbuSOBDJ1TxERyp4nkg',
    appId: '1:874445302227:web:6238dda2cd3c16e68b2726',
    messagingSenderId: '874445302227',
    projectId: 'code-burguer',
    authDomain: 'code-burguer.firebaseapp.com',
    storageBucket: 'code-burguer.firebasestorage.app',
    measurementId: 'G-952RJD18KH',
  );
}
